name: TWRP Builder + Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  DEVICE_BRAND: xiaomi
  DEVICE_CODENAME: lake
  TWRP_BRANCH: twrp-12.1

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
    - name: Checkout Script Repo
      uses: actions/checkout@v4

    # ===== DISK SPACE OPTIMIZATIONS =====
    - name: Free Up Disk Space (Initial)
      run: |
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/boost
        df -h  # Check remaining space

    - name: Set up Build Environment (Minimal)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends \
          bc bison build-essential ccache curl flex git gnupg gperf \
          liblz4-tool libncurses5-dev libssl-dev libxml2 lzop m4 python3 python3-pip zip
        
        # Install repo tool (minimal)
        mkdir -p ~/bin
        curl -s https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+rx ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Initialize TWRP Repo (Shallow)
      run: |
        mkdir -p ~/twrp && cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git \
          -b $TWRP_BRANCH --depth=1
        repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j2  # Reduced parallelism

    - name: Clone Device Tree (Shallow)
      run: |
        mkdir -p ~/twrp/device/$DEVICE_BRAND/$DEVICE_CODENAME
        git clone --depth=1 --single-branch \
          https://github.com/mdhaaib200520/redmi14c-lake-twrp_device-tree.git \
          ~/twrp/device/$DEVICE_BRAND/$DEVICE_CODENAME

    - name: Build TWRP (Reduced Parallelism)
      run: |
        cd ~/twrp
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch twrp_$DEVICE_CODENAME-eng
        mka -j2 recoveryimage  # Reduced to 2 parallel jobs

    - name: Clean Up Before Artifact
      run: |
        sudo rm -rf ~/twrp/.repo ~/twrp/out/.lock
        df -h

    - name: Prepare Release Assets
      run: |
        cd ~/twrp/out/target/product/$DEVICE_CODENAME
        mv recovery.img TWRP-$DEVICE_CODENAME-$(date +'%Y%m%d').img
        echo "BUILD_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-${{ env.DEVICE_CODENAME }}
        path: ~/twrp/out/target/product/${{ env.DEVICE_CODENAME }}/TWRP-${{ env.DEVICE_CODENAME }}-${{ env.BUILD_DATE }}.img

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: TWRP-${{ env.DEVICE_CODENAME }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: "TWRP ${{ env.BUILD_DATE }} for ${{ env.DEVICE_CODENAME }}"
        body: |
          Unofficial TWRP build for ${{ env.DEVICE_BRAND }} ${{ env.DEVICE_CODENAME }}
          - Build date: ${{ env.BUILD_DATE }}
          - Source: [Device Tree](https://github.com/mdhaaib200520/redmi14c-lake-twrp_device-tree.git)
        files: |
          TWRP-${{ env.DEVICE_CODENAME }}-${{ env.BUILD_DATE }}.img
