name: TWRP Build CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/ubports-ci/android-build:main

    steps:
    - name: Checkout Device Tree
      uses: actions/checkout@v3
      with:
        path: device

    - name: Initialize TWRP Build Environment
      run: |
        mkdir -p ~/android/twrp
        cd ~/android/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
        repo sync -j$(nproc) --force-sync --no-clone-bundle --no-tags

    - name: Copy Device Tree
      run: |
        mkdir -p ~/android/twrp/device/<brand>/<codename>
        cp -r device/* ~/android/twrp/device/<brand>/<codename>/

    - name: Build TWRP
      run: |
        cd ~/android/twrp
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch twrp_<codename>-eng
        mka recoveryimage

    - name: Upload Recovery Image
      uses: actions/upload-artifact@v3
      with:
        name: TWRP-recovery.img
        path: ~/android/twrp/out/target/product/<codename>/recovery.img
