name: Build TWRP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop openjdk-8-jdk pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8

    - name: Initialize repo
      run: |
        mkdir -p ~/twrp
        cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
        repo sync --force-sync --no-tags --no-clone-bundle -j$(nproc)

    - name: Clone device tree
      run: |
        cd ~/twrp
        git clone https://github.com/mdhaaib200520/redmi14c-lake-twrp_device-tree.git

    - name: Start build
      run: |
        cd ~/twrp
        export ALLOW_MISSING_DEPENDENCIES=true
        . build/envsetup.sh
        lunch omni_<codename>-eng
        mka recoveryimage

    - name: Upload recovery
      uses: actions/upload-artifact@v3
      with:
        name: recovery.img
        path: ~/twrp/out/target/product/<codename>/recovery.img
